#ifndef LUNACOLORS_H
#define LUNACOLORS_H

#define LUNA_COLOR_BLACK        0xFF000000
#define LUNA_COLOR_WHITE        0xFFFFFFFF

#define LUNA_COLOR_RED          0xFFFF0000
#define LUNA_COLOR_GREEN        0xFF00FF00
#define LUNA_COLOR_BLUE         0xFF0000FF

#define LUNA_COLOR_YELLOW       0xFFFFFF00
#define LUNA_COLOR_PURPLE       0xFFFF00FF
#define LUNA_COLOR_CYAN         0xFF00FFFF

#define LUNA_COLOR_GREY         0xFF555555

#endif